# 1. Load the libraries


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
os.chdir('/content/drive/MyDrive/Colab Notebooks/Projects/Loan Prediction')
os.listdir()

['Loan Prediction.ipynb', 'credit_risk_dataset.csv', 'loan.pdf']

In [ ]:
df=pd.read_csv('credit_risk_dataset.csv')

In [ ]:
df.head()

person_age  person_income person_home_ownership  person_emp_length  \
0          22          59000                  RENT              123.0   
1          21           9600                   OWN                5.0   
2          25           9600              MORTGAGE                1.0   
3          23          65500                  RENT                4.0   
4          24          54400                  RENT                8.0   

  loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
0    PERSONAL          D      35000          16.02            1   
1   EDUCATION          B       1000          11.14            0   
2     MEDICAL          C       5500          12.87            1   
3     MEDICAL          C      35000          15.23            1   
4     MEDICAL          C      35000          14.27            1   

   loan_percent_income cb_person_default_on_file  cb_person_cred_hist_length  
0                 0.59                         Y                           3  
1                 0.10                         N                           2  
2                 0.57                         N                           3  
3                 0.53                         N                           2  
4                 0.55                         Y                           4

In [ ]:
df.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [ ]:
df['person_home_ownership'].unique()

array(['RENT', 'OWN', 'MORTGAGE', 'OTHER'], dtype=object)

In [ ]:
df['person_home_ownership']=df["person_home_ownership"].replace(["RENT","OWN","MORTGAGE","OTHER"],[4,3,2,1])

In [ ]:
df['loan_intent'].unique()

array(['PERSONAL', 'EDUCATION', 'MEDICAL', 'VENTURE', 'HOMEIMPROVEMENT',
       'DEBTCONSOLIDATION'], dtype=object)

In [ ]:
df['loan_intent']=df["loan_intent"].replace(['PERSONAL', 'EDUCATION', 'MEDICAL', 'VENTURE', 'HOMEIMPROVEMENT','DEBTCONSOLIDATION'],[6,5,4,3,2,1])

In [ ]:
df.head()

person_age  person_income  person_home_ownership  person_emp_length  \
0          22          59000                      4              123.0   
1          21           9600                      3                5.0   
2          25           9600                      2                1.0   
3          23          65500                      4                4.0   
4          24          54400                      4                8.0   

   loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
0            6          D      35000          16.02            1   
1            5          B       1000          11.14            0   
2            4          C       5500          12.87            1   
3            4          C      35000          15.23            1   
4            4          C      35000          14.27            1   

   loan_percent_income cb_person_default_on_file  cb_person_cred_hist_length  
0                 0.59                         Y                           3  
1                 0.10                         N                           2  
2                 0.57                         N                           3  
3                 0.53                         N                           2  
4                 0.55                         Y                           4

In [ ]:
#separate input and output
Y=df["loan_status"]
X=df[['person_age','person_income','person_home_ownership','loan_intent','loan_amnt']]

In [ ]:
#Perform the train test split
from sklearn.model_selection import train_test_split as split
x_train,x_test,y_train,y_test=split(X,Y,test_size=0.25,random_state=0)

In [ ]:
#Data Transformation on Numerical Data : Standardization

#Import Class
from sklearn.preprocessing import StandardScaler

#Create object for StandardScaler class
scaler= StandardScaler()

x_train_transformed=scaler.fit_transform(x_train)
print(x_train_transformed.shape, x_train_transformed, sep="\n\n\n\n")

x_test_transformed=scaler.transform(x_test)
print(x_test_transformed.shape, x_test_transformed, sep="\n\n\n\n")

(24435, 5)



[[-0.90502355  0.20446501 -1.12945209  1.39368515 -0.37272786]
 [ 0.36086321  0.00815001 -1.12945209 -0.9870546   0.06222409]
 [-0.43031602 -0.11024305  0.95060231 -0.9870546   1.10610877]
 ...
 [-0.90502355 -0.4222329   0.95060231  0.20331527 -0.09594025]
 [-0.74678771 -0.36937886  0.95060231 -0.39186967  0.06222409]
 [-0.74678771 -0.49018809 -0.08942489 -0.39186967  0.21248022]]
(8146, 5)



[[-0.58855186 -0.37994966  0.95060231  0.79850021 -1.13982493]
 [-0.58855186  0.27997079  0.95060231  0.20331527  2.43468927]
 [-0.58855186  0.32527425 -1.12945209  0.20331527 -0.57043329]
 ...
 [ 0.36086321 -0.21836731 -1.12945209  1.39368515 -0.09594025]
 [-0.58855186  0.02325116 -1.12945209  0.79850021 -0.57043329]
 [-0.43031602 -0.03715346  0.95060231 -0.9870546   1.64386754]]


In [ ]:
cols=['person_age','person_income','person_home_ownership','loan_intent','loan_amnt']

In [ ]:
#standarization
from sklearn.preprocessing import StandardScaler
scale=StandardScaler()
x_train_transformed=pd.DataFrame(scale.fit_transform(x_train),columns=cols,index=x_train.index)
x_test_transformed=pd.DataFrame(scale.transform(x_test),columns=cols,index=x_test.index)

x_train_transformed.head()

person_age  person_income  person_home_ownership  loan_intent  \
12231   -0.905024       0.204465              -1.129452     1.393685   
23891    0.360863       0.008150              -1.129452    -0.987055   
1191    -0.430316      -0.110243               0.950602    -0.987055   
8463    -0.588552      -0.127760              -1.129452    -1.582240   
17638   -0.588552      -0.308974               0.950602     1.393685   

       loan_amnt  
12231  -0.372728  
23891   0.062224  
1191    1.106109  
8463   -0.412269  
17638  -0.574387

In [ ]:
# Model Building using Logistic Regression
from sklearn.linear_model import LogisticRegression
LR_Classifier=LogisticRegression()
LR_Classifier.fit(x_train_transformed,y_train)

LogisticRegression()

In [ ]:
from sklearn import metrics
# logistic Regression
y_test_predicted=LR_Classifier.predict(x_test_transformed)
metrics.accuracy_score(y_test,y_test_predicted)

0.8358703658237172

In [ ]:
# Model Building using KNN Classifier
from sklearn.neighbors import KNeighborsClassifier
KNN_Classifier=KNeighborsClassifier()
KNN_Classifier.fit(x_train_transformed,y_train)

KNeighborsClassifier()

In [ ]:
# Model Building using Decision Tree
from sklearn.tree import DecisionTreeClassifier
DT_Classifier=DecisionTreeClassifier()
DT_Classifier.fit(x_train_transformed,y_train)

DecisionTreeClassifier()

In [ ]:
# Model Building using Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
RFC_Classifier=RandomForestClassifier()
RFC_Classifier.fit(x_train_transformed,y_train)

RandomForestClassifier()

In [ ]:
# Model Building using Suport Vector Classifier
from sklearn.svm import SVC
sv_Classifier=SVC()
sv_Classifier.fit(x_train_transformed,y_train)

SVC()

In [ ]:
# KNN Classifer
y_test_predicted=KNN_Classifier.predict(x_test_transformed)
metrics.accuracy_score(y_test,y_test_predicted)

0.8406579916523447

In [ ]:
# KNN Classifer
y_test_predicted=KNN_Classifier.predict(x_test_transformed)
metrics.accuracy_score(y_test,y_test_predicted)

0.8406579916523447

In [ ]:
# Decision Tree Classifier
y_test_predicted=DT_Classifier.predict(x_test_transformed)
metrics.accuracy_score(y_test,y_test_predicted)

0.8282592683525657

In [ ]:
# Random Forest Classifier
y_test_predicted=RFC_Classifier.predict(x_test_transformed)
metrics.accuracy_score(y_test,y_test_predicted)

0.8795727964645225

In [ ]:
# Suport Vector Classifier
y_test_predicted=sv_Classifier.predict(x_test_transformed)
metrics.accuracy_score(y_test,y_test_predicted)

0.8521973974957034

In [ ]:
# Random Forest have best accuracy for that algorithm